# Generated by Django 5.0.6 on 2024-06-28 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_location_alter_event_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendee',
        ),
    ]
